name: Continuous Integration

on: [push]

jobs:
  build_and_test:
    name: 'Build & Test'

    runs-on: ubuntu-latest

    services:
      openldap-sasl:
        image: ldapts/openldap
        ports:
          - 1389:1389
          - 1636:1636

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run build
    - run: npm test
      env:
        CI: true
